# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./Vector.h \
    ./maingui.h \
    ./Calculator.h \
    ./classes.h \
    ./Space.h
SOURCES += ./Calculator.cpp \
    ./classes.cpp \
    ./main.cpp \
    ./maingui.cpp \
    ./Vector.cpp \
    ./Space.cpp
FORMS += ./maingui.ui
RESOURCES += maingui.qrc
